### ISSUE TITLE
panic when generating from a config that doesn't have a tag_specification and is trying to add an e2e test

### ISSUE THREAD

**Issue by csrwng** [openshift/ci-operator-prowgen#61]
I added an openshift_installer_src to the Hive configuration (https://github.com/openshift/release/pull/2719), and tried to generate prow jobs from it. However ci-operator-prowgen panics at: https://github.com/openshift/ci-operator-prowgen/blob/master/cmd/ci-operator-prowgen/main.go#L383 most likely because there is no ReleaseTagConfiguration in my config.

Should the config have a tag_specification? and where should it point to?

**Comment by bbguimaraes** [comment]
That should have resulted in a validation error:

https://github.com/openshift/ci-operator/blob/e56fa2a89d8d1f999476da848f3b2bb796d567e0/pkg/api/config.go#L237-L239

As you said, it is because the configuration is missing a `tag_specification`. It is required for `openshift_installer_src` tests because that's where the RPMs used to deploy the cluster come from.

**Comment by csrwng** [comment]
@bbguimaraes so we had removed the `tag_specification` based on your feedback https://github.com/openshift/release/pull/1877 Should we re-add it? What should we put in it?

**Comment by bbguimaraes** [comment]
I don't remember the context, but I believe that was because only promotion was necessary.

`tag_specification` and `promotion` are not mutually exclusive — although the latter defaults to the former — and can point to different `ImageStream`s. In this case, you want `tag_specification` to be the `origin-v4.0` release `IS` (so you get the release RPMs to deploy the test cluster) and `promotion` to point to your `IS` (as it is now, so your images are not promoted to the release IS).

**Comment by csrwng** [comment]
Thank you @bbguimaraes. I've now added the tag_specification and I'm able to generate the job config. Will close this issue and continue on https://github.com/openshift/release/pull/2719

/close

**Comment by bbguimaraes** [comment]
Now that I've had more time to look into this, it is actually a problem. Tests that use the installer to deploy a cluster do not need the release RPMs (and, consequently, `tag_specification`), contrary to what I said before and to tests that use `openshift-ansible`.

The validation is correct, but `prowgen` incorrectly assumes every template test has `tag_specification` set, resulting in the error initially reported.

@csrwng: for now let's keep your configuration as it is, then we can remove `tag_specification` when I correct the issue.

/reopen
